<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWbnU0lR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWbnU0lR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWbnU0lR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWbnU0lR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWbnU0lR\App_KernelDevDebugContainer([
    'container.build_hash' => 'WbnU0lR',
    'container.build_id' => 'a121d88a',
    'container.build_time' => 1706371085,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWbnU0lR');
